name: Preview DNS

on:
  pull_request:
    paths:
      - 'dns/dnsconfig.js'

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: DNSControl preview
        uses: koenrh/dnscontrol-action@v3
        id: dnscontrol_preview
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        with:
          args: preview

          config_file: 'dns/dnscontrol.js'
          creds_file: 'dns/creds.json'
      - name: Preview pull request comment
        uses: unsplash/comment-on-pr@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: |
            ```
            ${{ steps.dnscontrol_preview.outputs.preview_comment }}
            ```
          check_for_duplicate_msg: true
